name: Luacheck

on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1