name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  version:
    name: Create next version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: |
          npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: 'Kozoaku'
          GIT_AUTHOR_EMAIL: '93962386+Kozoaku@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'Kozoaku'
          GIT_COMMITTER_EMAIL: '93962386+Kozoaku@users.noreply.github.com'
        run: |
          npx semantic-release
  
  package:
    name: Run BigWigs Packager
    runs-on: ubuntu-latest
    needs: ['version']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package
        uses: BigWigsMods/packager@v2
        with:
          args: -S
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
