name: Release

on:
  push:
    tags:
      - "**"

jobs:
  package:
    name: Run BigWigs Packager
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package
        uses: BigWigsMods/packager@v2
        with:
          args: -S
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}