name: Build

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - "[0-9]+.[0-9]+.x"
      - "[0-9]+.x.x"
      - "[0-9].x"
    paths-ignore:
      - '.github/**'
      - 'docs/**'

jobs:
  version:
    name: Create next version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release
        run: |
          npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_CREDENTIALS }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
          GIT_AUTHOR_NAME: 'Kozoaku'
          GIT_AUTHOR_EMAIL: '93962386+Kozoaku@users.noreply.github.com'
          GIT_COMMITTER_NAME: 'Kozoaku'
          GIT_COMMITTER_EMAIL: '93962386+Kozoaku@users.noreply.github.com'
        run: |
          npx semantic-release

