name: Build

on:
  push:
    branches:
      - main
      - beta
      - alpha
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'CHANGELOG.md'

jobs:
  version:
    name: Create next version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Semantic Release
        run: |
          npm install semantic-release @semantic-release/git @semantic-release/changelog -D

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.event.pusher.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.pusher.email }}
          GIT_COMMITTER_NAME: 'Kozoaku'
          GIT_COMMITTER_EMAIL: '93962386+Kozoaku@users.noreply.github.com'
        run: |
          npx semantic-release

